language: node_js
node_js: 
  - "stable"
before_script:
   - npm install
after_script: 
./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
cache:
  directories:
    - "node_modules"
